### ISSUE TITLE
[React] Booleans don't get converted correctly 

### ISSUE THREAD

**Issue by no-creative-name** [ionic-team/stencil-ds-output-targets#123]
When passing a boolean prop to a wrapped stencil component, I noticed two problems.
`
            <StencilPopup
                isOpen={isPopupOpen}
                stringProp="Yeah"
`
(isPopupOpen is a false boolean)
`
<stencil-popup
    isopen="false"
    stringprop="Yeah"
    string-prop="Yeah"
`

1. The boolean on the resulting stencil component is set to "false" when isPopupOpen is false. In my understanding it should be "true" or "" when true and not set at all when false.
2. String & number props that are set as camelCase in react are added in kebab-case on the resulting stencil component, but boolean props are not. Is this on purpose? Should the props on the react component be passed in camelCase in the first place (which is autosuggested by the TS interface)?

If you lack information, please tell me. I'm happy to provide more. 😊

**Comment by TRMW** [comment]
My understanding based on [this](https://stackoverflow.com/a/31164090) is that React has some logic to conditionally add/remove Boolean attributes on built-in HTML elements such as `input` and `button` (so that if you pass `disabled={false}` the `disabled` attribute is not added to the element at all), but has no such logic for custom element tags, resulting in the behavior described here (`disabled="false"` being added to the element, which is truthy).

It could be helpful for Stencil's React output target to add that translation, since it does know which props are intended to be Booleans.

Thoughts on this? I'd be happy to take a pass at implementing, but could use some logic on the proper place to do so.

**Comment by TRMW** [comment]
Would love to hear any thoughts from those who have contributed most to the React target so far, such as @jthoms1 and @manucorporat. Also thanks for you work on this project!

**Comment by scabana** [comment]
As a workaround, you can alter the output of `attachProps.ts`, replace `if (propType === 'string') {` with 

```
        if (propType === 'boolean') {
          if (newProps[name] === true) {
            node.setAttribute(camelToDashCase(name), camelToDashCase(name));
          } else {
            node.removeAttribute(camelToDashCase(name));
          }
        } else if (propType === 'string') {
```

To see how you can do this: https://github.com/ionic-team/stencil-ds-output-targets/issues/81#issuecomment-721447514

**Comment by ghaagsma** [comment]
Thanks for the workaround @scabana!

It would be great to resolve this in Stencil directly, so client applications/libraries don't all have to duplicate this solution to provide a React-friendly solution for HTML-attribute-bound optional boolean properties in component interfaces. Any word from the core team on whether this will be prioritized?

**Comment by TRMW** [comment]
@scabana the link you included seems to link to an unrelated Angular issue. Did you mean to link somewhere else?

**Comment by scabana** [comment]
> @scabana the link you included seems to link to an unrelated Angular issue. Did you mean to link somewhere else?

It's a link to the right comment on how you could end up patching `attachProps.ts` after the react output target runs. I can't share the whole solution I came up with but I tried to expose the parts I used to build my solution. How to get the custom raplace code in place and what to replace from and to.

**Comment by WickyNilliams** [comment]
As I discuss in #149 it's not as simple as omitting a boolean attr when value is `false`. If you omit a boolean attr when false, then there is no way to change the value of a prop whose default is `true`. You could instead set the JS property, but this can result in flickering during loading, since the `false` value is only picked up after the component has rendered. 

From what I gather, React is (finally!) starting to look at improving support for web components. Some of the questions/problems here may become redundant as this progresses, so it's worth keeping on eye on this issue: https://github.com/facebook/react/issues/11347. It looks like they are considering these improvements for release in React v18!

**Comment by estankovic** [comment]
> As a workaround, you can alter the output of `attachProps.ts`, replace `if (propType === 'string') {` with
> 
> ```
>         if (propType === 'boolean') {
>           if (newProps[name] === true) {
>             node.setAttribute(camelToDashCase(name), camelToDashCase(name));
>           } else {
>             node.removeAttribute(camelToDashCase(name));
>           }
>         } else if (propType === 'string') {
> ```
> 
> To see how you can do this: [#81 (comment)](https://github.com/ionic-team/stencil-ds-output-targets/issues/81#issuecomment-721447514)

Hello everyone, I would like to ask, whether is there a particular reason why this was not implemented. Are there any problems with proposed solution?

**Comment by christian-bromann** [comment]
This should be resolved with the latest `@stencil/react-output-target`. If it still poses an issue for someone please let me know and I will re-open it.
