### ISSUE TITLE
Question: Can I publish to an npm registry and use the components generated by ReactOutputTarget?

### ISSUE THREAD

**Issue by nvegater** [ionic-team/stencil-ds-output-targets#130]
1. I created a standard stencil project to make web components and be able to export them to a react application.

2. I would like the react application to consume the components produced by reactOutputTarget.

3. The build process generates the custom JSX components but there are multiple problems:

The generated components...
- have a dependency to componentCorePackage, which is the package itself. (what is this supposed to mean?)
- have a dependency to react. should I install React in my stencil project to get this working?

Where (inside of my stencil project) should I generate the react components to be able to publish them to npm, and consume them in a react app?

I followed https://stenciljs.com/docs/react 
But I dont want to have any extra package to serve the react components, I want to be able to export the react components from the Stencil project. Is this possible?

Thanks! :) let me know if it makes sense what im asking

**Comment by nvegater** [comment]
I was able to workaround this by copy pasting the reactOutput output in my react application.
Hopefully there is a way of serving this react components together with the web components :)

**Comment by sean-perkins** [comment]
Hello, I know this issue is older, but wanted to follow up with context before closing. 

I would not recommend exporting the react wrappers from your Stencil project. The react wrappers should be generated against a separate package (either your app that is directly consuming them, inside a mono-repo structure; or the library that you are going to publish/distribute). 

We do this within Ionic Framework. `@ionic/react` is the react library of wrappers and misc. react specific utilities. It has a dependency on our Stencil web components (`@ionic/core`). Consumers will only install `@ionic/react` into their react applications when using our components.
