### ISSUE TITLE
[Angular] generates proxies.ts contains errors for components that have Events

### ISSUE THREAD

**Issue by 123city** [ionic-team/stencil-ds-output-targets#139]
### Problem
I'm having trouble generating the output for the Angular library, using @stencil/angular-output-target. 
When running _npm run build_, the generated proxies.ts file contains errors for the components that include EventEmitters.

### Error
Cannot find module '@siteplanet/planet-css/dist/custom-elements/components/planet-crud/planet-crud' or its corresponding type declarations
```
import { PlanetCrud as IPlanetCrud } from '@siteplanet/planet-css/dist/custom-elements/components/planet-crud/planet-crud';
export declare interface PlanetCrud extends Components.PlanetCrud {}
```

The generate custom-elements folder only contains two files, an index.d.ts and a index.js, and no "components" folder.

### Stencil configuration
```
angularOutputTarget({
      componentCorePackage: '@siteplanet/planet-css',
      directivesProxyFile: '../planet-ng/src/directives/proxies.ts',
      valueAccessorConfigs: angularValueAccessorBindings,
}),
{
    type: 'dist',
},
{
    type: 'dist-custom-elements-bundle',
},
```

**Comment by DavidWiesner** [comment]
I also encountered this problem. Stencil added the `dist-custom-elements-bundle` output target and within also some paths. The right import path in the `proxies.ts`file should be in your case:
`import { PlanetCrud as IPlanetCrud } from '@siteplanet/planet-css/dist/types/components/planet-crud/planet-crud';`

So `.../dist/types/...` instead of `.../dist/custom-elements/...`

Because this file is generated on every build, you need to replace this after every build. As workaround you can change your scripts in the `package.json` like this:

```json
  "scripts": {
    "build-stencil": "stencil build --docs",
    "build": "npm run build-stencil && npm run build-fix-angular-proxies",
    "build-fix-angular-proxies": "perl -i -pe 's#/dist/custom-elements/#/dist/types/#' 'path/to/your/proxies.ts'",
    ...
  }
```

**Comment by 123city** [comment]
Thanks for the workaround! 
Should I leave the issue open until there is are permanent fix?

**Comment by DavidWiesner** [comment]
Another workaround is to change the types definition in your package.json to `"types": "dist/types/index.d.ts",` but I am not sure what implications that may have. I think you should leave this issue open, because it's not resolved yet

**Comment by shavenwalrus** [comment]
Thanks for the workaround. There is another problem for me in proxies.ts though.

I have this event handler in my component:

`@Event() somethingHappened: EventEmitter<void>;`

In proxies.ts this becomes:

`somethingHappened!: IMyComponent['somethingHappened'];`

Unfortunately I get the error:

`Property 'somethingHappened' does not exist on type 'MyComponent'.ts(2339)`

This is what my-component.d.ts looks like:

![image](https://user-images.githubusercontent.com/8065548/109896823-5a53f380-7cdd-11eb-80ad-070d676c5238.png)

Notice the the event is not there.

**Comment by Jan-Ole** [comment]
@DavidWiesner  Thank you so much!
I was wondering what is happening here. Your post saved my day.

**Comment by lodybo** [comment]
> Another workaround is to change the types definition in your package.json to `"types": "dist/types/index.d.ts",` but I am not sure what implications that may have. I think you should leave this issue open, because it's not resolved yet

Doing this will "solve" the wrong path being generated in `proxies.ts`, but it might screw up your `defineCustomElements` import in your NgModule.

If you have this import in your `module.ts` file in your Angular library:
```typescript
import { defineCustomElements } from '@siteplanet/planet-css';
/*
  Will fail with the TS compiler complaining that 
  "TS2305: Module '"../../../../node_modules/@siteplanet/planet-css/dist/types"' has no exported member 'defineCustomElements'."
*/
```
that will fail, because `defineCustomElements` is only defined in the typing declaration formed by `dist-custom-elements-bundle`.

A workaround for this issue is pointing the import to that folder, which will be `dist/custom-elements` if you ahven't changed that path in your `stencil.config.ts`:
```typescript
import { defineCustomElements } from '@siteplanet/planet-css/dist/custom-elements';
```

Now everything should build without issues.

**Comment by splitinfinities** [comment]
I'm going to add this to the upcoming docs update for the Angular integration page. The interfaces.d.ts pattern noted above is the preferred solution.
