### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by klh** [ionic-team/stencil-ds-output-targets#201]
Guys and Gals,
You need to be a lot more communicative with the miletones and planning on this Repo - it's abandonware right now.

It would be nice if you could respond to this with a concise plan on how you:

1.  Plan to move this forward
2. Integrate all the PRs that are stale,
3. Fix the current outputs (that are semi broken now).

This is hanging in limbo - let me know if you need assistance getting this of the ground.

twitter: @klhougesen

**Comment by GLoganDR** [comment]
Commenting on this because my team is asking the same questions about this. The current versions are very off from the latest output targets and latest versions of the target frameworks and libraries. It would be very helpful to have this updated to help us work out some of these bugs we're seeing when we try to upgrade to the latest output targets.

When trying to use @stencil/angular-output-target v0.2.0, I get a ton of errors and everything just crashes in the console. When I use 0.0.5, it works fine. So I think the probable reason is that the newer versions of Angular build differently and this output target is the only one that works alongside of the 8.x versions of Angular. 

Please update! :D

**Comment by splitinfinities** [comment]
Hey folks! Ionic teams are actively working on these bindings, ironing out the details of our repo's and how best to prioritize issues and PR's, as well as updating docs. All of these are big focus areas for us this quarter. Strategically, as the new team has been spinning up, we've been focused on learning about core and the health of the code there. We will be folding this repo into Stencil's process over this quarter once Framework v6 is released. The Angular and React docs are on my plate to have a first draft by the end of this week. 

Can you all do me a huge favor for your next steps? First, detail explicitly what you are bumping into when you open an issue. What PR's are helpful for you? Signal boost the errors that you are bumping into with reactions. We need signal to understand what to prioritize. Please also understand that Framework 6 is releasing soon and that includes all of these updated framework bindings which now use the `dist-custom-elements` output target. So we're all well aware that we need to improve documentation and smooth over the last few rough edges when generated components are used in real environments. 

We're searching for positive signals and GitHub issues like this can be demoralizing to teams of people who are working really hard in iteration each day to improve quite a large ecosystem and community. I want to remind you that there are people on the other end of this code, and I'm super proud of their hard work. 

The way I choose to read this issue is that you're all super engaged community members and - just like myself as a super engaged community member - you want Stencil and its ecosystem to thrive, be successful, and deliver on its promise of being an awesome component compiler. I really appreciate your enthusiasm for Stencil. I'm excited to be able to share more about the hard work happening behind the scenes in order to give the community the confidence in Stencil that we all want. Thank you for the patience and understanding! We'll get there.
