### ISSUE TITLE
task: Deprecate `ReactComponentContext` and `manipulatePropsFunction`

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/stencil-ds-output-targets#243]
These props were introduced as an abstraction to custom behavior that Ionic Framework was taking advantage of ~2 years ago. These props are no longer used by the Ionic Framework project.

Proposal:
- Deprecate `ReactComponentContext `from `createReactComponent`
- Deprecate `manipulatePropsFunctions` from `createReactComponent`

Current:
```ts
export const IonAccordion = /*@__PURE__*/createReactComponent<JSX.IonAccordion, HTMLIonAccordionElement>('ion-accordion', undefined, undefined, defineIonAccordion);
```

After:
```ts
export const IonAccordion = /*@__PURE__*/createReactComponent<JSX.IonAccordion, HTMLIonAccordionElement>('ion-accordion', defineIonAccordion);
```

If your project is making use of these properties, please explain your use case below.

**Comment by ZakaryCode** [comment]
Hope that `manulatePropsFunctions` can be supported as soon as possible, so that developers can decide whether to import parameters such as `dangrouslySetInnerHTML` by overriding `propsToPass`.

At present, manually modify `components.ts` and inject the `manulatePropsFunction` prop into `createReactComponent`, which is inconvenient.

**Comment by christian-bromann** [comment]
fixed in https://github.com/ionic-team/stencil-ds-output-targets/pull/432
