### ISSUE TITLE
bug: Angular Output 'scam' proxies import type 'Component' path 

### ISSUE THREAD

**Issue by maldago** [ionic-team/stencil-ds-output-targets#406]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.7.2

### Stencil Framework Output Target

Angular

### Stencil Framework Output Target Version

0.8.3

### Current Behavior

Using dist-custom-elements, with the option `auto-define-custom-elements', targeting the output type `'scam'` for `angularOutputTarget`;

The generated proxies.ts module  contains an `import type { Components } from ...`  but the path that is generated has no exported member. The paths to the component.js files are correct.

### Expected Behavior

Expect the path to resolve the type.

### Steps to Reproduce

- fork the code reproduction 
- `yarn`
- `nx run reprowebcomps:build`
- observe the output `proxies.ts` @ `libs/ng-repro/src/directives/proxies.ts`

- if you need to rerun the build step, clear the nx cache with `nx reset`

### Code Reproduction URL

https://github.com/maldago/stencil-angular-output-target

**Comment by sean-perkins** [comment]
Hello @maldago, thanks for this issue.

The angular output target currently only supports the default configuration for `customElementsExportBehavior`. When the Angular component wrappers are constructed, they will automatically define the custom element. 

Using `customElementsExportBehavior: "auto-define-custom-elements"` is not a configuration we planned for and I don't believe it makes sense when aligned to how Angular components are defined. For example it could define the custom element for a child web component that you have an Angular wrapper for, but the Angular component may never be imported/defined. This leads to confusion and potential bugs in your application, since the web component may render correctly, but angular bindings will not work as expected on that element.

**Comment by christian-bromann** [comment]
@maldago let me know if you have any further questions.
