### ISSUE TITLE
Cannot find module `loader` or its corresponding type declarations.

### ISSUE THREAD

**Issue by ps011** [ionic-team/stencil-ds-output-targets#49]
> @my-scope/component-library-react@0.0.1 tsc /Users/<user>/Projects/component-library/packages/component-library-react
> tsc -p .

src/components.ts:8:54 - error TS2307: Cannot find module '@my-scope/component-library/loader' or its corresponding type declarations.

8 import { defineCustomElements, applyPolyfills } from '@my-scope/component-library/loader';
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.



The above error was thrown when I tried to compile the react output of my component library which was generated using '@stencil/react-output-target'.

However, I was able to figure out the error. The import statement should be 

`8 import { defineCustomElements, applyPolyfills } from '@my-scope/component-library/dist/loader';`

instead of 

8 import { defineCustomElements, applyPolyfills } from '@my-scope/component-library/loader';

**Comment by jthoms1** [comment]
Could you provide the version of stencil you are using?

**Comment by ps011** [comment]
1.9.0

**Comment by sentience** [comment]
This is working for me with the latest Stencil (1.16.1) and React Output Target (0.0.7). Stencil's default configuration for the dist output target now writes the loader directory to the root of the root of the project, rather than as a subdirectory of dist.

<img width="270" alt="CleanShot 2020-07-10 at 12 29 14@2x" src="https://user-images.githubusercontent.com/89772/87109845-06595200-c2a9-11ea-9db8-8b433729f7f0.png">

**Comment by christian-bromann** [comment]
Thanks for providing a fix @ps011 , closing!
